import type { CatalogRecipe } from "./recipes";

/**
 * Fikko's own recipes, shipped with the app. Nutrition is an estimate per
 * serving, worked out from typical values for the ingredients listed, and the
 * page labels it as approximate.
 *
 * `contains` lists common allergens from the ingredients as written (soy
 * sauce and most noodles, wraps and oats count as gluten; oyster sauce as
 * shellfish). Optional add-ins count; serving suggestions like "bread, to
 * serve" don't.
 *
 * `art` picks the tile's illustration (see RecipeArt): these recipes have no
 * photos, so each tile gets a soft colour and an icon for its main ingredient.
 */
export const RECIPE_CATALOG: CatalogRecipe[] = [
  {
    key: "fikko-lemon-herb-chicken",
    title: "Lemon herb chicken traybake",
    description: "Juicy chicken thighs roasted on one tray with peppers, red onion and cherry tomatoes.",
    tags: ["chicken", "high-protein", "low-carb"],
    contains: [],
    art: "chicken",
    minutes: 40, servings: 4, calories: 390, macros: { protein: 36, carbs: 12, fat: 21 },
    ingredients: [
      "8 skinless, boneless chicken thighs",
      "2 peppers, cut into chunks",
      "1 red onion, cut into wedges",
      "250 g cherry tomatoes",
      "2 tbsp olive oil",
      "1 lemon, zest and juice",
      "3 garlic cloves, crushed",
      "1 tsp dried oregano",
      "Small bunch of parsley, chopped",
    ],
    steps: [
      "Heat the oven to 200°C (180°C fan).",
      "Mix the oil, lemon zest and juice, garlic, oregano, salt and pepper. Toss the chicken in half of it.",
      "Spread the peppers and onion on a large tray, toss with the rest of the dressing, then sit the chicken on top.",
      "Roast for 25 minutes, add the tomatoes, and roast 10 minutes more until the chicken is cooked through.",
      "Scatter with parsley and serve with the tray juices.",
    ],
  },
  {
    key: "fikko-chicken-stir-fry",
    title: "15-minute chicken and veg stir-fry",
    description: "A fast, light weeknight stir-fry with a ginger and soy sauce.",
    tags: ["chicken", "high-protein", "low-fat", "quick"],
    contains: ["gluten", "soy"],
    art: "chicken",
    minutes: 15, servings: 2, calories: 340, macros: { protein: 38, carbs: 24, fat: 9 },
    ingredients: [
      "2 chicken breasts, thinly sliced",
      "1 tbsp cornflour",
      "1 tbsp vegetable oil",
      "1 head of broccoli, in small florets",
      "1 red pepper, sliced",
      "100 g sugar snap peas",
      "2 tbsp reduced-salt soy sauce",
      "1 tbsp honey",
      "Thumb of ginger and 2 garlic cloves, grated",
      "Spring onions, to serve",
    ],
    steps: [
      "Toss the chicken in the cornflour with a pinch of salt.",
      "Heat the oil in a wok until very hot and stir-fry the chicken for 4–5 minutes until golden. Lift out.",
      "Add the broccoli, pepper and sugar snaps with a splash of water and stir-fry for 3 minutes.",
      "Mix the soy, honey, ginger and garlic, pour in with the chicken and toss for 1 minute until glossy.",
      "Top with sliced spring onions.",
    ],
  },
  {
    key: "fikko-greek-chicken-wraps",
    title: "Greek chicken wraps with tzatziki",
    description: "Oregano chicken, crunchy salad and a quick garlicky yoghurt sauce.",
    tags: ["chicken", "high-protein"],
    contains: ["dairy", "gluten"],
    art: "wrap",
    minutes: 25, servings: 4, calories: 420, macros: { protein: 35, carbs: 38, fat: 13 },
    ingredients: [
      "500 g chicken breast, in strips",
      "1 tbsp olive oil",
      "1 tsp dried oregano and 1 tsp smoked paprika",
      "4 wholemeal wraps",
      "150 g Greek yoghurt (0% fat works well)",
      "¼ cucumber, grated and squeezed dry",
      "1 small garlic clove, grated",
      "Little gem lettuce, tomatoes and red onion, sliced",
    ],
    steps: [
      "Toss the chicken with the oil, oregano, paprika, salt and pepper.",
      "Cook in a hot pan for 6–8 minutes until browned and cooked through.",
      "Stir the cucumber and garlic into the yoghurt with a pinch of salt to make tzatziki.",
      "Warm the wraps, fill with salad and chicken, spoon over tzatziki and roll up.",
    ],
  },
  {
    key: "fikko-chicken-sweet-potato-curry",
    title: "Chicken, sweet potato and spinach curry",
    description: "A gentle, family-friendly curry made lighter with half-fat coconut milk.",
    tags: ["chicken"],
    contains: [],
    art: "curry",
    minutes: 45, servings: 4, calories: 430, macros: { protein: 33, carbs: 34, fat: 17 },
    ingredients: [
      "600 g chicken thighs, diced",
      "2 sweet potatoes, peeled and cubed",
      "1 onion, chopped",
      "2 tbsp medium curry paste",
      "400 ml tin reduced-fat coconut milk",
      "200 ml chicken stock",
      "100 g baby spinach",
      "1 tbsp oil and a squeeze of lime",
    ],
    steps: [
      "Soften the onion in the oil for 5 minutes, then stir in the curry paste for 1 minute.",
      "Add the chicken and cook until sealed all over.",
      "Add the sweet potato, coconut milk and stock. Simmer for 25 minutes until the potato is tender.",
      "Stir in the spinach until wilted, add the lime and season. Serve with rice or naan.",
    ],
  },
  {
    key: "fikko-beef-broccoli-bowl",
    title: "Beef and broccoli rice bowls",
    description: "Takeaway-style sticky beef with plenty of greens over rice.",
    tags: ["beef", "high-protein"],
    contains: ["gluten", "shellfish", "soy"],
    art: "beef",
    minutes: 25, servings: 4, calories: 480, macros: { protein: 34, carbs: 52, fat: 14 },
    ingredients: [
      "400 g lean beef steak, thinly sliced",
      "1 tbsp cornflour",
      "1 tbsp vegetable oil",
      "2 heads of broccoli, in florets",
      "3 tbsp reduced-salt soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp brown sugar",
      "2 garlic cloves and a thumb of ginger, grated",
      "240 g rice (uncooked weight)",
      "Sesame seeds, to serve",
    ],
    steps: [
      "Cook the rice following the packet instructions.",
      "Toss the beef in cornflour. Sear in the hot oil in batches for 1–2 minutes and lift out.",
      "Stir-fry the broccoli with a splash of water for 3 minutes.",
      "Mix the soy, oyster sauce, sugar, garlic and ginger, add with the beef and bubble for 1 minute.",
      "Spoon over the rice and scatter with sesame seeds.",
    ],
  },
  {
    key: "fikko-lean-beef-chilli",
    title: "Lean beef and bean chilli",
    description: "A big batch of smoky chilli bulked out with beans and peppers. Freezes well.",
    tags: ["beef", "high-protein", "low-fat"],
    contains: [],
    art: "stew",
    minutes: 60, servings: 6, calories: 360, macros: { protein: 31, carbs: 32, fat: 10 },
    ingredients: [
      "500 g lean (5% fat) beef mince",
      "1 onion and 2 peppers, chopped",
      "3 garlic cloves, crushed",
      "2 tsp ground cumin, 2 tsp smoked paprika, 1 tsp chilli powder",
      "2 × 400 g tins chopped tomatoes",
      "400 g tin kidney beans, drained",
      "400 g tin black beans, drained",
      "1 tbsp tomato purée",
      "1 beef stock cube",
    ],
    steps: [
      "Brown the mince in a large dry pan, breaking it up. Tip out any fat.",
      "Add the onion, peppers and garlic and cook for 5 minutes.",
      "Stir in the spices and tomato purée for 1 minute.",
      "Add the tomatoes, crumbled stock cube and a small glass of water. Simmer for 30 minutes.",
      "Add the beans and simmer for 10 minutes more. Season and serve.",
    ],
  },
  {
    key: "fikko-beef-lettuce-wraps",
    title: "Korean-style beef lettuce cups",
    description: "Sweet, savoury mince spooned into crisp lettuce: low-carb and ready fast.",
    tags: ["beef", "low-carb", "quick", "high-protein"],
    contains: ["gluten", "soy"],
    art: "salad",
    minutes: 20, servings: 3, calories: 330, macros: { protein: 30, carbs: 10, fat: 19 },
    ingredients: [
      "400 g lean beef mince",
      "2 tbsp gochujang (Korean chilli paste)",
      "1 tbsp reduced-salt soy sauce",
      "1 tsp sesame oil",
      "2 garlic cloves, grated",
      "2 little gem lettuces, leaves separated",
      "1 carrot and ¼ cucumber, cut into matchsticks",
      "Spring onions and sesame seeds, to serve",
    ],
    steps: [
      "Brown the mince in a hot pan for 6–8 minutes and drain off any fat.",
      "Stir in the gochujang, soy, sesame oil and garlic and cook for 2 minutes.",
      "Spoon into the lettuce leaves and top with carrot, cucumber, spring onion and sesame seeds.",
    ],
  },
  {
    key: "fikko-pork-pineapple-skewers",
    title: "Pork and pineapple skewers",
    description: "Sticky, sweet-sour skewers for the grill or a hot griddle pan.",
    tags: ["pork", "low-fat", "high-protein"],
    contains: ["gluten", "soy"],
    art: "pork",
    minutes: 30, servings: 4, calories: 290, macros: { protein: 31, carbs: 22, fat: 8 },
    ingredients: [
      "500 g pork tenderloin, in chunks",
      "½ fresh pineapple, in chunks",
      "1 red onion and 1 red pepper, in chunks",
      "2 tbsp reduced-salt soy sauce",
      "1 tbsp honey",
      "1 tsp Chinese five-spice",
      "1 garlic clove, crushed",
    ],
    steps: [
      "Mix the soy, honey, five-spice and garlic, and toss the pork in it. Leave for 10 minutes if you can.",
      "Thread the pork, pineapple, onion and pepper onto skewers (soak wooden ones first).",
      "Cook on a hot grill or griddle for 10–12 minutes, turning and brushing with the marinade, until the pork is cooked through.",
    ],
  },
  {
    key: "fikko-ginger-pork-noodles",
    title: "Garlic ginger pork noodles",
    description: "Quick pork mince noodles with pak choi and a punchy sauce.",
    tags: ["pork", "quick"],
    contains: ["eggs", "gluten", "soy"],
    art: "noodles",
    minutes: 20, servings: 2, calories: 520, macros: { protein: 32, carbs: 58, fat: 17 },
    ingredients: [
      "250 g lean pork mince",
      "150 g dried egg noodles",
      "2 pak choi, quartered",
      "Thumb of ginger and 3 garlic cloves, grated",
      "2 tbsp reduced-salt soy sauce",
      "1 tbsp rice vinegar",
      "1 tsp chilli oil (optional)",
      "Spring onions, to serve",
    ],
    steps: [
      "Cook the noodles, adding the pak choi for the last minute. Drain.",
      "Fry the pork in a hot pan until browned and crisp at the edges.",
      "Add the ginger and garlic for 1 minute, then the soy, vinegar and chilli oil.",
      "Toss through the noodles and pak choi, and top with spring onions.",
    ],
  },
  {
    key: "fikko-salmon-greens-quinoa",
    title: "Baked salmon with greens and quinoa",
    description: "Omega-3-rich salmon with a bright lemon and dill yoghurt.",
    tags: ["fish", "high-protein"],
    contains: ["dairy"],
    art: "fish",
    minutes: 25, servings: 2, calories: 520, macros: { protein: 38, carbs: 34, fat: 24 },
    ingredients: [
      "2 salmon fillets",
      "100 g quinoa",
      "150 g tenderstem broccoli",
      "100 g frozen peas",
      "1 lemon",
      "3 tbsp Greek yoghurt",
      "Small bunch of dill, chopped",
      "1 tsp olive oil",
    ],
    steps: [
      "Heat the oven to 200°C (180°C fan). Rinse the quinoa and simmer it for 15 minutes.",
      "Put the salmon on a lined tray, drizzle with the oil, add lemon slices and bake for 12–15 minutes.",
      "Steam the broccoli and peas for 4 minutes.",
      "Mix the yoghurt, dill and a squeeze of lemon. Serve the salmon on the quinoa and greens with the sauce.",
    ],
  },
  {
    key: "fikko-tuna-bean-salad",
    title: "Tuna, white bean and tomato salad",
    description: "A no-cook lunch that keeps you full for hours.",
    tags: ["fish", "low-fat", "quick", "high-protein"],
    contains: [],
    art: "salad",
    minutes: 10, servings: 2, calories: 330, macros: { protein: 33, carbs: 30, fat: 8 },
    ingredients: [
      "2 × 145 g tins tuna in spring water, drained",
      "400 g tin cannellini beans, drained",
      "200 g cherry tomatoes, halved",
      "½ red onion, finely sliced",
      "Handful of rocket",
      "1 tbsp olive oil and 1 tbsp red wine vinegar",
      "1 tsp Dijon mustard",
    ],
    steps: [
      "Whisk the oil, vinegar and mustard with a pinch of salt and pepper.",
      "Toss the beans, tomatoes and onion in the dressing.",
      "Fold through the tuna and rocket and serve.",
    ],
  },
  {
    key: "fikko-cod-tacos",
    title: "Crispy cod tacos with lime slaw",
    description: "Oven-baked fish in a light crumb, with a zingy crunchy slaw.",
    tags: ["fish", "low-fat"],
    contains: ["dairy", "eggs", "gluten"],
    art: "taco",
    minutes: 30, servings: 4, calories: 380, macros: { protein: 28, carbs: 45, fat: 9 },
    ingredients: [
      "4 cod fillets, cut into strips",
      "50 g panko breadcrumbs",
      "1 tsp smoked paprika",
      "1 egg, beaten",
      "8 small corn or flour tortillas",
      "¼ red cabbage, finely shredded",
      "1 carrot, grated",
      "2 limes",
      "3 tbsp light soured cream and coriander, to serve",
    ],
    steps: [
      "Heat the oven to 220°C (200°C fan).",
      "Dip the cod in egg, then in the panko mixed with paprika. Bake on a lined tray for 12–15 minutes.",
      "Toss the cabbage and carrot with the juice of 1 lime and a pinch of salt.",
      "Fill the warm tortillas with slaw and fish, add soured cream, coriander and lime wedges.",
    ],
  },
  {
    key: "fikko-prawn-courgette-linguine",
    title: "Garlic prawn and courgette linguine",
    description: "Half pasta, half courgette ribbons: all the comfort, fewer calories.",
    tags: ["fish", "quick", "high-protein"],
    contains: ["gluten", "shellfish"],
    art: "shrimp",
    minutes: 20, servings: 2, calories: 450, macros: { protein: 32, carbs: 52, fat: 11 },
    ingredients: [
      "150 g linguine",
      "200 g raw king prawns",
      "2 courgettes, peeled into ribbons",
      "3 garlic cloves, sliced",
      "1 red chilli, sliced",
      "1 tbsp olive oil",
      "1 lemon, zest and juice",
      "Parsley, chopped",
    ],
    steps: [
      "Cook the linguine, adding the courgette ribbons for the last minute. Keep a mug of pasta water.",
      "Gently fry the garlic and chilli in the oil for 1 minute, add the prawns and cook until pink.",
      "Toss in the pasta and courgette with the lemon and a splash of pasta water.",
      "Season and finish with parsley.",
    ],
  },
  {
    key: "fikko-veggie-omelette",
    title: "Loaded veggie omelette",
    description: "A protein-packed breakfast in under 10 minutes.",
    tags: ["eggs", "vegetarian", "low-carb", "quick", "breakfast", "high-protein"],
    contains: ["dairy", "eggs"],
    art: "egg",
    minutes: 10, servings: 1, calories: 310, macros: { protein: 24, carbs: 6, fat: 21 },
    ingredients: [
      "3 eggs",
      "Handful of spinach",
      "4 cherry tomatoes, quartered",
      "2 mushrooms, sliced",
      "20 g feta, crumbled",
      "1 tsp olive oil",
    ],
    steps: [
      "Fry the mushrooms in the oil for 2 minutes, then add the spinach until wilted.",
      "Beat the eggs with salt and pepper and pour over the vegetables.",
      "Cook gently, pulling the edges in, until almost set. Add the tomatoes and feta.",
      "Fold in half and slide onto a plate.",
    ],
  },
  {
    key: "fikko-shakshuka",
    title: "Easy shakshuka",
    description: "Eggs poached in a spiced tomato and pepper sauce. Great for brunch.",
    tags: ["eggs", "vegetarian", "breakfast"],
    contains: ["eggs"],
    art: "egg-pan",
    minutes: 30, servings: 2, calories: 330, macros: { protein: 18, carbs: 24, fat: 17 },
    ingredients: [
      "4 eggs",
      "1 onion and 1 red pepper, sliced",
      "2 garlic cloves, crushed",
      "1 tsp ground cumin and 1 tsp smoked paprika",
      "400 g tin chopped tomatoes",
      "1 tbsp olive oil",
      "Coriander or parsley and crusty bread, to serve",
    ],
    steps: [
      "Soften the onion and pepper in the oil for 8 minutes, add the garlic and spices for 1 minute.",
      "Add the tomatoes and simmer for 10 minutes until thick. Season.",
      "Make 4 hollows and crack in the eggs. Cover and cook for 6–8 minutes until the whites are set.",
      "Scatter with herbs and serve with bread.",
    ],
  },
  {
    key: "fikko-overnight-oats",
    title: "Berry overnight oats",
    description: "Stir together the night before and breakfast is waiting.",
    tags: ["vegetarian", "breakfast", "low-fat"],
    contains: ["dairy", "gluten"],
    art: "oats",
    minutes: 5, servings: 1, calories: 340, macros: { protein: 17, carbs: 52, fat: 7 },
    ingredients: [
      "50 g rolled oats",
      "120 ml semi-skimmed milk (or any milk)",
      "3 tbsp Greek yoghurt",
      "1 tsp chia seeds",
      "Handful of berries",
      "1 tsp honey (optional)",
    ],
    steps: [
      "Stir the oats, milk, yoghurt and chia together in a jar.",
      "Cover and chill overnight.",
      "In the morning, top with berries and a drizzle of honey.",
    ],
  },
  {
    key: "fikko-yoghurt-parfait",
    title: "Greek yoghurt crunch pot",
    description: "Layers of creamy yoghurt, fruit and crunchy oats: a high-protein snack or breakfast.",
    tags: ["vegetarian", "breakfast", "quick", "high-protein"],
    contains: ["dairy", "gluten", "nuts"],
    art: "cherry",
    minutes: 5, servings: 1, calories: 290, macros: { protein: 22, carbs: 34, fat: 7 },
    ingredients: [
      "200 g 0% fat Greek yoghurt",
      "30 g granola",
      "Handful of raspberries or chopped fruit",
      "1 tsp honey",
      "A few chopped nuts (optional)",
    ],
    steps: [
      "Spoon half the yoghurt into a glass, add half the fruit and granola.",
      "Repeat the layers and finish with honey and nuts.",
    ],
  },
  {
    key: "fikko-chickpea-spinach-stew",
    title: "Chickpea and spinach stew",
    description: "A warming, budget-friendly stew with smoked paprika.",
    tags: ["vegan", "vegetarian", "low-fat"],
    contains: [],
    art: "stew-green",
    minutes: 30, servings: 4, calories: 280, macros: { protein: 12, carbs: 38, fat: 7 },
    ingredients: [
      "2 × 400 g tins chickpeas, drained",
      "1 onion, chopped",
      "3 garlic cloves, crushed",
      "2 tsp smoked paprika and 1 tsp ground cumin",
      "400 g tin chopped tomatoes",
      "300 ml vegetable stock",
      "200 g spinach",
      "1 tbsp olive oil",
    ],
    steps: [
      "Soften the onion in the oil for 5 minutes, then add the garlic and spices.",
      "Add the chickpeas, tomatoes and stock and simmer for 15 minutes.",
      "Stir in the spinach until wilted and season well. Serve with bread or rice.",
    ],
  },
  {
    key: "fikko-lentil-bolognese",
    title: "Lentil bolognese",
    description: "A plant-based take on the classic, rich with tomatoes and herbs.",
    tags: ["vegan", "vegetarian", "low-fat", "high-protein"],
    contains: ["gluten"],
    art: "pasta",
    minutes: 40, servings: 4, calories: 470, macros: { protein: 22, carbs: 80, fat: 6 },
    ingredients: [
      "200 g dried green or brown lentils, rinsed",
      "1 onion, 1 carrot and 1 celery stick, finely chopped",
      "2 garlic cloves, crushed",
      "2 × 400 g tins chopped tomatoes",
      "1 tbsp tomato purée",
      "1 tsp dried oregano",
      "500 ml vegetable stock",
      "300 g wholewheat spaghetti",
    ],
    steps: [
      "Soften the onion, carrot and celery in a splash of water or oil for 8 minutes. Add the garlic.",
      "Add the lentils, tomatoes, purée, oregano and stock. Simmer for 25–30 minutes until the lentils are tender.",
      "Cook the spaghetti, drain and toss with the sauce.",
    ],
  },
  {
    key: "fikko-tofu-stir-fry",
    title: "Crispy tofu and vegetable stir-fry",
    description: "Golden tofu with crunchy veg in a sticky sauce.",
    tags: ["vegan", "vegetarian", "quick", "high-protein"],
    contains: ["gluten", "soy"],
    art: "tofu",
    minutes: 20, servings: 2, calories: 390, macros: { protein: 24, carbs: 28, fat: 19 },
    ingredients: [
      "280 g firm tofu, pressed and cubed",
      "1 tbsp cornflour",
      "1 tbsp vegetable oil",
      "1 pepper and 1 carrot, sliced",
      "150 g green beans",
      "2 tbsp reduced-salt soy sauce",
      "1 tbsp maple syrup",
      "1 tsp sesame oil and a grated garlic clove",
    ],
    steps: [
      "Toss the tofu in cornflour and fry in the oil until golden on all sides. Lift out.",
      "Stir-fry the vegetables for 4 minutes.",
      "Add the soy, maple syrup, sesame oil and garlic, return the tofu and toss to coat.",
    ],
  },
  {
    key: "fikko-black-bean-bowls",
    title: "Black bean and sweet potato bowls",
    description: "Roasted sweet potato, spiced beans, rice and a creamy avocado lime sauce.",
    tags: ["vegan", "vegetarian"],
    contains: [],
    art: "bowl",
    minutes: 35, servings: 4, calories: 480, macros: { protein: 14, carbs: 78, fat: 13 },
    ingredients: [
      "2 sweet potatoes, cubed",
      "2 × 400 g tins black beans, drained",
      "1 tsp ground cumin and 1 tsp smoked paprika",
      "200 g rice (uncooked weight)",
      "1 avocado",
      "1 lime",
      "Handful of coriander",
      "1 tbsp olive oil and 200 g sweetcorn",
    ],
    steps: [
      "Roast the sweet potato in the oil and half the spices at 200°C (180°C fan) for 25 minutes.",
      "Cook the rice. Warm the beans with the rest of the spices and a splash of water.",
      "Blend or mash the avocado with the lime juice, coriander and a little water to a sauce.",
      "Build bowls with rice, beans, sweet potato and sweetcorn, and spoon over the sauce.",
    ],
  },
  {
    key: "fikko-halloumi-traybake",
    title: "Roasted vegetable and halloumi traybake",
    description: "Colourful roasted veg topped with golden halloumi.",
    tags: ["vegetarian"],
    contains: ["dairy"],
    art: "veg",
    minutes: 40, servings: 3, calories: 450, macros: { protein: 20, carbs: 30, fat: 27 },
    ingredients: [
      "225 g halloumi, sliced",
      "1 courgette and 1 aubergine, in chunks",
      "2 peppers, in chunks",
      "1 red onion, in wedges",
      "400 g tin chickpeas, drained",
      "1 tbsp olive oil",
      "1 tsp za'atar or dried mixed herbs",
      "1 lemon",
    ],
    steps: [
      "Heat the oven to 200°C (180°C fan).",
      "Toss the vegetables and chickpeas with the oil, herbs and seasoning and roast for 25 minutes.",
      "Lay the halloumi on top and roast for 10 minutes more until golden.",
      "Squeeze over the lemon before serving.",
    ],
  },
  {
    key: "fikko-banana-oat-pancakes",
    title: "Banana oat pancakes",
    description: "Three-ingredient pancakes with no added sugar.",
    tags: ["vegetarian", "breakfast", "quick"],
    contains: ["eggs", "gluten"],
    art: "pancake",
    minutes: 15, servings: 2, calories: 300, macros: { protein: 12, carbs: 42, fat: 9 },
    ingredients: [
      "2 ripe bananas",
      "2 eggs",
      "60 g rolled oats",
      "Pinch of cinnamon",
      "A little oil for the pan",
      "Berries and yoghurt, to serve",
    ],
    steps: [
      "Blend the bananas, eggs, oats and cinnamon until smooth.",
      "Heat a lightly oiled pan and cook small spoonfuls for 1–2 minutes each side.",
      "Serve stacked with berries and a spoon of yoghurt.",
    ],
  },
  {
    key: "fikko-egg-fried-cauli-rice",
    title: "Egg-fried cauliflower rice",
    description: "All the flavour of egg-fried rice with a fraction of the carbs.",
    tags: ["eggs", "vegetarian", "low-carb", "quick"],
    contains: ["eggs", "gluten", "soy"],
    art: "egg",
    minutes: 15, servings: 2, calories: 250, macros: { protein: 15, carbs: 14, fat: 15 },
    ingredients: [
      "1 cauliflower, grated or blitzed into rice",
      "3 eggs, beaten",
      "100 g frozen peas",
      "1 carrot, finely diced",
      "3 spring onions, sliced",
      "2 tbsp reduced-salt soy sauce",
      "1 tbsp vegetable oil and 1 tsp sesame oil",
    ],
    steps: [
      "Stir-fry the carrot and peas in the vegetable oil for 2 minutes.",
      "Add the cauliflower rice and stir-fry for 4–5 minutes until just tender.",
      "Push to one side, scramble the eggs in the space, then mix everything together.",
      "Season with the soy and sesame oil and top with spring onions.",
    ],
  },
];
