-- Migration check: is everything from schema.sql and migrations 002–032 in this database?
-- Generated 2026-10-07 from the migration files (405 objects).
-- Read-only. Returns one row per missing object, plus any public table
-- without row-level security. One row saying "All good" means nothing is missing.

with expected(file, kind, sch, tbl, name) as (values
  ('schema.sql', 'table', 'public', null, 'profiles'),
  ('schema.sql', 'column', 'public', 'profiles', 'user_id'),
  ('schema.sql', 'column', 'public', 'profiles', 'name'),
  ('schema.sql', 'column', 'public', 'profiles', 'date_of_birth'),
  ('schema.sql', 'column', 'public', 'profiles', 'gender'),
  ('schema.sql', 'column', 'public', 'profiles', 'height_cm'),
  ('schema.sql', 'column', 'public', 'profiles', 'weight_kg'),
  ('schema.sql', 'column', 'public', 'profiles', 'activity_level'),
  ('schema.sql', 'column', 'public', 'profiles', 'calorie_goal'),
  ('schema.sql', 'column', 'public', 'profiles', 'water_goal'),
  ('schema.sql', 'column', 'public', 'profiles', 'sleep_goal'),
  ('schema.sql', 'column', 'public', 'profiles', 'updated_at'),
  ('schema.sql', 'function', 'public', null, 'handle_new_user'),
  ('schema.sql', 'trigger', 'auth', 'users', 'on_auth_user_created'),
  ('schema.sql', 'table', 'public', null, 'habit_entries'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'id'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'user_id'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'category'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'date'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'value'),
  ('schema.sql', 'column', 'public', 'habit_entries', 'note'),
  ('schema.sql', 'table', 'public', null, 'custom_habits'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'id'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'user_id'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'name'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'unit'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'target'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'color'),
  ('schema.sql', 'column', 'public', 'custom_habits', 'icon'),
  ('schema.sql', 'table', 'public', null, 'custom_habit_entries'),
  ('schema.sql', 'column', 'public', 'custom_habit_entries', 'id'),
  ('schema.sql', 'column', 'public', 'custom_habit_entries', 'custom_habit_id'),
  ('schema.sql', 'column', 'public', 'custom_habit_entries', 'user_id'),
  ('schema.sql', 'column', 'public', 'custom_habit_entries', 'date'),
  ('schema.sql', 'column', 'public', 'custom_habit_entries', 'value'),
  ('schema.sql', 'table', 'public', null, 'medications'),
  ('schema.sql', 'column', 'public', 'medications', 'id'),
  ('schema.sql', 'column', 'public', 'medications', 'user_id'),
  ('schema.sql', 'column', 'public', 'medications', 'name'),
  ('003_medication_schedule.sql', 'column', 'public', 'medications', 'time_of_day'),
  ('004_custom_foods.sql', 'table', 'public', null, 'custom_foods'),
  ('004_custom_foods.sql', 'column', 'public', 'custom_foods', 'id'),
  ('004_custom_foods.sql', 'column', 'public', 'custom_foods', 'user_id'),
  ('004_custom_foods.sql', 'column', 'public', 'custom_foods', 'name'),
  ('004_custom_foods.sql', 'column', 'public', 'custom_foods', 'calories_per_100g'),
  ('004_custom_foods.sql', 'column', 'public', 'custom_foods', 'created_at'),
  ('002_food_log_items.sql', 'table', 'public', null, 'food_log_items'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'id'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'user_id'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'date'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'meal'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'name'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'grams'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'calories_per_100g'),
  ('002_food_log_items.sql', 'column', 'public', 'food_log_items', 'calories'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'onboarding_completed_at'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'primary_goal'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'target_weight_kg'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'weekly_rate_kg'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'dietary_pattern'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'allergies'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'wearable'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'tracking_style'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'reminders_enabled'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'height_unit'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'weight_unit'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'bmr'),
  ('005_onboarding.sql', 'column', 'public', 'profiles', 'tdee'),
  ('006_hardening.sql', 'index', 'public', null, 'habit_entries_user_date_idx'),
  ('006_hardening.sql', 'index', 'public', null, 'custom_habits_user_idx'),
  ('006_hardening.sql', 'index', 'public', null, 'custom_habit_entries_user_date_idx'),
  ('006_hardening.sql', 'index', 'public', null, 'medications_user_idx'),
  ('006_hardening.sql', 'index', 'public', null, 'food_log_items_user_date_idx'),
  ('006_hardening.sql', 'policy', 'public', 'profiles', 'profiles are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'habit_entries', 'habit_entries are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'custom_habits', 'custom_habits are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'custom_habit_entries', 'custom_habit_entries are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'medications', 'medications are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'food_log_items', 'food_log_items are self-owned'),
  ('006_hardening.sql', 'policy', 'public', 'custom_foods', 'custom_foods are self-owned'),
  ('007_community.sql', 'table', 'public', null, 'community_posts'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'id'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'user_id'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'author_name'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'topic'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'body'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'hidden'),
  ('007_community.sql', 'column', 'public', 'community_posts', 'created_at'),
  ('007_community.sql', 'table', 'public', null, 'community_comments'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'id'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'post_id'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'user_id'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'author_name'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'body'),
  ('007_community.sql', 'column', 'public', 'community_comments', 'created_at'),
  ('007_community.sql', 'table', 'public', null, 'community_cheers'),
  ('007_community.sql', 'column', 'public', 'community_cheers', 'post_id'),
  ('007_community.sql', 'column', 'public', 'community_cheers', 'user_id'),
  ('007_community.sql', 'column', 'public', 'community_cheers', 'created_at'),
  ('007_community.sql', 'table', 'public', null, 'community_reports'),
  ('007_community.sql', 'column', 'public', 'community_reports', 'id'),
  ('007_community.sql', 'column', 'public', 'community_reports', 'post_id'),
  ('007_community.sql', 'column', 'public', 'community_reports', 'user_id'),
  ('007_community.sql', 'column', 'public', 'community_reports', 'reason'),
  ('007_community.sql', 'column', 'public', 'community_reports', 'created_at'),
  ('007_community.sql', 'index', 'public', null, 'community_posts_feed_idx'),
  ('007_community.sql', 'index', 'public', null, 'community_posts_user_idx'),
  ('007_community.sql', 'index', 'public', null, 'community_comments_post_idx'),
  ('007_community.sql', 'index', 'public', null, 'community_comments_user_idx'),
  ('007_community.sql', 'index', 'public', null, 'community_cheers_user_idx'),
  ('007_community.sql', 'function', 'public', null, 'community_display_name'),
  ('007_community.sql', 'function', 'public', null, 'community_before_insert'),
  ('007_community.sql', 'trigger', 'public', 'community_posts', 'community_posts_before_insert'),
  ('007_community.sql', 'trigger', 'public', 'community_comments', 'community_comments_before_insert'),
  ('007_community.sql', 'function', 'public', null, 'community_after_report'),
  ('007_community.sql', 'trigger', 'public', 'community_reports', 'community_reports_after_insert'),
  ('007_community.sql', 'policy', 'public', 'community_posts', 'community_posts created by author'),
  ('007_community.sql', 'policy', 'public', 'community_posts', 'community_posts deleted by author'),
  ('007_community.sql', 'policy', 'public', 'community_comments', 'community_comments created by author'),
  ('007_community.sql', 'policy', 'public', 'community_comments', 'community_comments deleted by author'),
  ('007_community.sql', 'policy', 'public', 'community_cheers', 'community_cheers readable by members'),
  ('007_community.sql', 'policy', 'public', 'community_cheers', 'community_cheers given by self'),
  ('007_community.sql', 'policy', 'public', 'community_cheers', 'community_cheers removed by self'),
  ('007_community.sql', 'policy', 'public', 'community_reports', 'community_reports filed by self'),
  ('008_recipes.sql', 'table', 'public', null, 'recipes'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'id'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'user_id'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'author_name'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'title'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'description'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'tags'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'ingredients'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'steps'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'minutes'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'servings'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'calories'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'photo_path'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'hidden'),
  ('008_recipes.sql', 'column', 'public', 'recipes', 'created_at'),
  ('008_recipes.sql', 'table', 'public', null, 'recipe_saves'),
  ('008_recipes.sql', 'column', 'public', 'recipe_saves', 'user_id'),
  ('008_recipes.sql', 'column', 'public', 'recipe_saves', 'recipe_key'),
  ('008_recipes.sql', 'column', 'public', 'recipe_saves', 'created_at'),
  ('008_recipes.sql', 'table', 'public', null, 'recipe_reports'),
  ('008_recipes.sql', 'column', 'public', 'recipe_reports', 'id'),
  ('008_recipes.sql', 'column', 'public', 'recipe_reports', 'recipe_id'),
  ('008_recipes.sql', 'column', 'public', 'recipe_reports', 'user_id'),
  ('008_recipes.sql', 'column', 'public', 'recipe_reports', 'reason'),
  ('008_recipes.sql', 'column', 'public', 'recipe_reports', 'created_at'),
  ('008_recipes.sql', 'index', 'public', null, 'recipes_feed_idx'),
  ('008_recipes.sql', 'index', 'public', null, 'recipes_user_idx'),
  ('008_recipes.sql', 'function', 'public', null, 'recipes_before_insert'),
  ('008_recipes.sql', 'trigger', 'public', 'recipes', 'recipes_before_insert'),
  ('008_recipes.sql', 'function', 'public', null, 'recipes_after_report'),
  ('008_recipes.sql', 'trigger', 'public', 'recipe_reports', 'recipe_reports_after_insert'),
  ('008_recipes.sql', 'policy', 'public', 'recipes', 'recipes created by author'),
  ('008_recipes.sql', 'policy', 'public', 'recipes', 'recipes deleted by author'),
  ('008_recipes.sql', 'policy', 'public', 'recipe_saves', 'recipe_saves are self-owned'),
  ('008_recipes.sql', 'policy', 'public', 'recipe_reports', 'recipe_reports filed by self'),
  ('008_recipes.sql', 'policy', 'storage', 'objects', 'recipe photos readable by members'),
  ('008_recipes.sql', 'policy', 'storage', 'objects', 'recipe photos uploaded to own folder'),
  ('008_recipes.sql', 'policy', 'storage', 'objects', 'recipe photos deleted by owner'),
  ('009_recipe_rewards.sql', 'column', 'public', 'recipes', 'save_count'),
  ('010_recipe_fixes.sql', 'function', 'public', null, 'recipes_reset_save_count'),
  ('009_recipe_rewards.sql', 'table', 'public', null, 'points_events'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'id'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'user_id'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'kind'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'points'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'recipe_id'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'dedupe'),
  ('009_recipe_rewards.sql', 'column', 'public', 'points_events', 'created_at'),
  ('009_recipe_rewards.sql', 'index', 'public', null, 'points_events_user_idx'),
  ('009_recipe_rewards.sql', 'policy', 'public', 'points_events', 'points_events readable by owner'),
  ('009_recipe_rewards.sql', 'table', 'public', null, 'featured_recipes'),
  ('009_recipe_rewards.sql', 'column', 'public', 'featured_recipes', 'week_start'),
  ('009_recipe_rewards.sql', 'column', 'public', 'featured_recipes', 'recipe_id'),
  ('009_recipe_rewards.sql', 'column', 'public', 'featured_recipes', 'saves'),
  ('009_recipe_rewards.sql', 'column', 'public', 'featured_recipes', 'created_at'),
  ('009_recipe_rewards.sql', 'policy', 'public', 'featured_recipes', 'featured_recipes readable by members'),
  ('009_recipe_rewards.sql', 'function', 'public', null, 'recipe_saves_after_insert'),
  ('009_recipe_rewards.sql', 'function', 'public', null, 'recipe_saves_after_delete'),
  ('009_recipe_rewards.sql', 'trigger', 'public', 'recipe_saves', 'recipe_saves_after_insert'),
  ('009_recipe_rewards.sql', 'trigger', 'public', 'recipe_saves', 'recipe_saves_after_delete'),
  ('010_recipe_fixes.sql', 'function', 'public', null, 'current_featured_recipe'),
  ('010_recipe_fixes.sql', 'trigger', 'public', 'recipes', 'recipes_reset_save_count'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'recipes', 'contains'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'food_log_items', 'protein_per_100g'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'food_log_items', 'carbs_per_100g'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'food_log_items', 'fat_per_100g'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'custom_foods', 'protein_per_100g'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'custom_foods', 'carbs_per_100g'),
  ('011_allergens_and_macros.sql', 'column', 'public', 'custom_foods', 'fat_per_100g'),
  ('012_device_sync.sql', 'table', 'public', null, 'device_connections'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'user_id'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'provider'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'access_token'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'refresh_token'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'expires_at'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'scopes'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'status'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'last_error'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'connected_at'),
  ('012_device_sync.sql', 'column', 'public', 'device_connections', 'last_synced_at'),
  ('012_device_sync.sql', 'table', 'public', null, 'oauth_states'),
  ('012_device_sync.sql', 'column', 'public', 'oauth_states', 'state'),
  ('012_device_sync.sql', 'column', 'public', 'oauth_states', 'user_id'),
  ('012_device_sync.sql', 'column', 'public', 'oauth_states', 'provider'),
  ('012_device_sync.sql', 'column', 'public', 'oauth_states', 'code_verifier'),
  ('012_device_sync.sql', 'column', 'public', 'oauth_states', 'created_at'),
  ('012_device_sync.sql', 'table', 'public', null, 'biometric_entries'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'user_id'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'metric'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'date'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'value'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'source'),
  ('012_device_sync.sql', 'column', 'public', 'biometric_entries', 'updated_at'),
  ('012_device_sync.sql', 'index', 'public', null, 'biometric_entries_user_date_idx'),
  ('012_device_sync.sql', 'policy', 'public', 'device_connections', 'device_connections readable by owner'),
  ('012_device_sync.sql', 'policy', 'public', 'biometric_entries', 'biometric_entries readable by owner'),
  ('013_deletion_grace_period.sql', 'column', 'public', 'profiles', 'deletion_scheduled_for'),
  ('013_deletion_grace_period.sql', 'index', 'public', null, 'profiles_deletion_scheduled_for_idx'),
  ('013_deletion_grace_period.sql', 'table', 'public', null, 'account_deletion_feedback'),
  ('013_deletion_grace_period.sql', 'column', 'public', 'account_deletion_feedback', 'id'),
  ('013_deletion_grace_period.sql', 'column', 'public', 'account_deletion_feedback', 'reason'),
  ('013_deletion_grace_period.sql', 'column', 'public', 'account_deletion_feedback', 'details'),
  ('013_deletion_grace_period.sql', 'column', 'public', 'account_deletion_feedback', 'created_at'),
  ('013_deletion_grace_period.sql', 'function', 'public', null, 'is_active_member'),
  ('013_deletion_grace_period.sql', 'policy', 'public', 'community_posts', 'community_posts readable by members'),
  ('013_deletion_grace_period.sql', 'policy', 'public', 'community_comments', 'community_comments readable by members'),
  ('013_deletion_grace_period.sql', 'policy', 'public', 'recipes', 'recipes readable by members'),
  ('014_ai_coach.sql', 'table', 'public', null, 'coach_messages'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_messages', 'id'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_messages', 'user_id'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_messages', 'role'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_messages', 'content'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_messages', 'created_at'),
  ('014_ai_coach.sql', 'index', 'public', null, 'coach_messages_user_created_idx'),
  ('014_ai_coach.sql', 'policy', 'public', 'coach_messages', 'coach_messages readable by owner'),
  ('014_ai_coach.sql', 'policy', 'public', 'coach_messages', 'coach_messages clearable by owner'),
  ('014_ai_coach.sql', 'table', 'public', null, 'coach_usage'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_usage', 'id'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_usage', 'user_id'),
  ('014_ai_coach.sql', 'column', 'public', 'coach_usage', 'created_at'),
  ('014_ai_coach.sql', 'index', 'public', null, 'coach_usage_user_created_idx'),
  ('014_ai_coach.sql', 'policy', 'public', 'coach_usage', 'coach_usage readable by owner'),
  ('015_faster_logging.sql', 'table', 'public', null, 'saved_meals'),
  ('015_faster_logging.sql', 'column', 'public', 'saved_meals', 'id'),
  ('015_faster_logging.sql', 'column', 'public', 'saved_meals', 'user_id'),
  ('015_faster_logging.sql', 'column', 'public', 'saved_meals', 'name'),
  ('015_faster_logging.sql', 'column', 'public', 'saved_meals', 'items'),
  ('015_faster_logging.sql', 'column', 'public', 'saved_meals', 'created_at'),
  ('015_faster_logging.sql', 'index', 'public', null, 'saved_meals_user_idx'),
  ('015_faster_logging.sql', 'policy', 'public', 'saved_meals', 'saved_meals are self-owned'),
  ('015_faster_logging.sql', 'column', 'public', 'custom_foods', 'barcode'),
  ('015_faster_logging.sql', 'index', 'public', null, 'custom_foods_user_barcode_idx'),
  ('016_admin_analytics.sql', 'table', 'public', null, 'admins'),
  ('016_admin_analytics.sql', 'column', 'public', 'admins', 'user_id'),
  ('016_admin_analytics.sql', 'column', 'public', 'admins', 'created_at'),
  ('016_admin_analytics.sql', 'function', 'public', null, 'is_admin'),
  ('016_admin_analytics.sql', 'table', 'public', null, 'analytics_views'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_views', 'day'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_views', 'site'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_views', 'path'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_views', 'views'),
  ('016_admin_analytics.sql', 'table', 'public', null, 'analytics_visitors'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'day'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'site'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'referrer'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'device'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'country'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_visitors', 'visitors'),
  ('016_admin_analytics.sql', 'table', 'public', null, 'analytics_seen'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_seen', 'day'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_seen', 'site'),
  ('016_admin_analytics.sql', 'column', 'public', 'analytics_seen', 'visitor'),
  ('016_admin_analytics.sql', 'function', 'public', null, 'track_page_view'),
  ('017_admin_mfa.sql', 'function', 'public', null, 'admin_stats'),
  ('017_admin_mfa.sql', 'function', 'public', null, 'admin_status'),
  ('018_medication_history.sql', 'column', 'public', 'medications', 'archived_at'),
  ('019_onboarding_focus.sql', 'column', 'public', 'profiles', 'dietary_patterns'),
  ('019_onboarding_focus.sql', 'column', 'public', 'profiles', 'goal_focus'),
  ('020_minimum_age.sql', 'function', 'public', null, 'enforce_minimum_age'),
  ('020_minimum_age.sql', 'trigger', 'public', 'profiles', 'profiles_minimum_age'),
  ('021_multiple_goals.sql', 'column', 'public', 'profiles', 'goals'),
  ('022_consent_records.sql', 'table', 'public', null, 'consent_records'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'id'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'user_id'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'consent_key'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'granted'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'policy_version'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'region'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'country'),
  ('022_consent_records.sql', 'column', 'public', 'consent_records', 'created_at'),
  ('022_consent_records.sql', 'index', 'public', null, 'consent_records_user_idx'),
  ('022_consent_records.sql', 'policy', 'public', 'consent_records', 'consent records are readable by their owner'),
  ('024_ai_costs.sql', 'table', 'public', null, 'ai_costs'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'id'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'user_id'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'feature'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'model'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'input_tokens'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'cache_read_tokens'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'cache_write_tokens'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'output_tokens'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'cost_usd'),
  ('024_ai_costs.sql', 'column', 'public', 'ai_costs', 'created_at'),
  ('024_ai_costs.sql', 'index', 'public', null, 'ai_costs_created_idx'),
  ('024_ai_costs.sql', 'index', 'public', null, 'ai_costs_user_created_idx'),
  ('024_ai_costs.sql', 'function', 'public', null, 'admin_ai_costs'),
  ('024_regional_foods.sql', 'table', 'public', null, 'regional_foods'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'id'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'source'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'source_id'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'name'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'name_local'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'category'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'calories_per_100g'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'protein_per_100g'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'carbs_per_100g'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'fat_per_100g'),
  ('024_regional_foods.sql', 'column', 'public', 'regional_foods', 'search_text'),
  ('025_my_fikko.sql', 'column', 'public', 'profiles', 'fikko_seed'),
  ('025_my_fikko.sql', 'column', 'public', 'profiles', 'fikko_planted_on'),
  ('025_my_fikko.sql', 'column', 'public', 'profiles', 'fikko_pot'),
  ('025_my_fikko.sql', 'column', 'public', 'profiles', 'fikko_companion'),
  ('026_ai_recipes.sql', 'table', 'public', null, 'ai_recipes'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'id'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'user_id'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'title'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'description'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'tags'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'contains'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'art'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'ingredients'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'have'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'buy'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'swaps'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'steps'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'minutes'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'servings'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'calories'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'protein'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'carbs'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'fat'),
  ('026_ai_recipes.sql', 'column', 'public', 'ai_recipes', 'created_at'),
  ('026_ai_recipes.sql', 'index', 'public', null, 'ai_recipes_user_created_idx'),
  ('026_ai_recipes.sql', 'policy', 'public', 'ai_recipes', 'ai_recipes are self-owned'),
  ('026_fikko_garden.sql', 'table', 'public', null, 'fikko_garden'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'id'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'user_id'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'seed'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'pot'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'companion'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'planted_on'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'harvested_on'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'complete_days'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'reward'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'tree_status'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'premium_month'),
  ('026_fikko_garden.sql', 'column', 'public', 'fikko_garden', 'created_at'),
  ('026_fikko_garden.sql', 'index', 'public', null, 'fikko_garden_user_idx'),
  ('026_fikko_garden.sql', 'index', 'public', null, 'fikko_garden_planting_idx'),
  ('026_fikko_garden.sql', 'policy', 'public', 'fikko_garden', 'fikko_garden readable by owner'),
  ('026_fikko_garden.sql', 'function', 'public', null, 'harvest_fikko'),
  ('027_fikko_scene.sql', 'column', 'public', 'profiles', 'fikko_scene'),
  ('028_wearable_beta.sql', 'table', 'public', null, 'wearable_beta'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'user_id'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'provider'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'google_email'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'status'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'requested_at'),
  ('028_wearable_beta.sql', 'column', 'public', 'wearable_beta', 'decided_at'),
  ('028_wearable_beta.sql', 'policy', 'public', 'wearable_beta', 'Members read their own beta request'),
  ('028_wearable_beta.sql', 'function', 'public', null, 'admin_wearable_beta'),
  ('028_wearable_beta.sql', 'function', 'public', null, 'admin_wearable_beta_decide'),
  ('029_admin_launch_metrics.sql', 'function', 'public', null, 'admin_launch_metrics'),
  ('030_founding_members.sql', 'table', 'public', null, 'founding_members'),
  ('030_founding_members.sql', 'column', 'public', 'founding_members', 'user_id'),
  ('030_founding_members.sql', 'column', 'public', 'founding_members', 'place'),
  ('030_founding_members.sql', 'column', 'public', 'founding_members', 'claimed_at'),
  ('030_founding_members.sql', 'column', 'public', 'founding_members', 'welcome_sent_at'),
  ('030_founding_members.sql', 'policy', 'public', 'founding_members', 'Members read their own founding place'),
  ('030_founding_members.sql', 'function', 'public', null, 'founding_places_total'),
  ('030_founding_members.sql', 'function', 'public', null, 'grant_founding_place'),
  ('030_founding_members.sql', 'function', 'public', null, 'claim_founding_place_on_setup'),
  ('030_founding_members.sql', 'trigger', 'public', 'profiles', 'claim_founding_place'),
  ('030_founding_members.sql', 'function', 'public', null, 'founding_places_left'),
  ('031_reminders.sql', 'table', 'public', null, 'reminder_settings'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'user_id'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'frequency'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'send_hour'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'time_zone'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'last_sent_on'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'unsubscribe_token'),
  ('031_reminders.sql', 'column', 'public', 'reminder_settings', 'updated_at'),
  ('031_reminders.sql', 'policy', 'public', 'reminder_settings', 'Members read their reminder settings'),
  ('031_reminders.sql', 'policy', 'public', 'reminder_settings', 'Members add their reminder settings'),
  ('031_reminders.sql', 'policy', 'public', 'reminder_settings', 'Members change their reminder settings'),
  ('031_reminders.sql', 'function', 'public', null, 'reminder_candidates'),
  ('032_rate_limits.sql', 'table', 'public', null, 'rate_limits'),
  ('032_rate_limits.sql', 'column', 'public', 'rate_limits', 'key'),
  ('032_rate_limits.sql', 'column', 'public', 'rate_limits', 'window_start'),
  ('032_rate_limits.sql', 'column', 'public', 'rate_limits', 'hits'),
  ('032_rate_limits.sql', 'function', 'public', null, 'rate_limit')
),
missing as (
  select e.file, e.kind, coalesce(e.tbl || '.', '') || e.name as object
  from expected e
  where not case e.kind
    when 'table'    then to_regclass(format('%I.%I', e.sch, e.name)) is not null
    when 'view'     then to_regclass(format('%I.%I', e.sch, e.name)) is not null
    when 'index'    then to_regclass(format('%I.%I', e.sch, e.name)) is not null
    when 'column'   then exists (select 1 from information_schema.columns c
                                 where c.table_schema = e.sch and c.table_name = e.tbl and c.column_name = e.name)
    when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                 where n.nspname = e.sch and p.proname = e.name)
    when 'trigger'  then exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                                 join pg_namespace n on n.oid = c.relnamespace
                                 where n.nspname = e.sch and c.relname = e.tbl and t.tgname = e.name)
    when 'policy'   then exists (select 1 from pg_policies p
                                 where p.schemaname = e.sch and p.tablename = e.tbl and p.policyname = e.name)
  end
  union all
  select '(security)', 'no row-level security', c.relname
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and not c.relrowsecurity
)
select * from missing
union all
select 'All good', (select count(*) from expected)::text || ' objects checked', 'nothing missing'
where not exists (select 1 from missing)
order by 1, 2, 3;
